import { ThemeProvider } from 'next-themes';
import { StylesProvider } from './styles-provider';
import '../../global.css';
import { Provider } from '@acme/provider';

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StylesProvider>
            <Provider>{children}</Provider>
          </StylesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
