/** @jsxImportSource react */
import '../../global.css';
import { Provider } from '@acme/provider';

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
